#!/bin/bash
# Setup access to Pearl NAS for PhotoPrism deployment

echo "Pearl NAS Access Setup"
echo "====================="
echo ""
echo "Pearl NAS IP: 192.168.100.212 (pearl.lan)"
echo ""
echo "To enable PhotoPrism to access photos on Pearl NAS, you need to:"
echo ""
echo "1. Add SSH public key to Pearl NAS (if using SSH for management):"
echo "   Copy this public key to claude@pearl ~/.ssh/authorized_keys:"
echo ""
cat ~/.ssh/claude_pearl_ed25519.pub
echo ""
echo "2. Configure NAS shares on Pearl:"
echo "   - Create or verify these shares exist:"
echo "     * /volume1/orico (or appropriate path for Orico storage)"
echo "     * /volume1/gdrive (or appropriate path for G Drive storage)"
echo ""
echo "3. Configure NFS exports on Pearl NAS:"
echo "   Add these lines to /etc/exports on Pearl:"
echo "   /volume1/orico 192.168.100.0/24(ro,sync,no_subtree_check,no_root_squash)"
echo "   /volume1/gdrive 192.168.100.0/24(ro,sync,no_subtree_check,no_root_squash)"
echo ""
echo "4. Or configure SMB shares (alternative to NFS):"
echo "   - Share name: orico"
echo "   - Share name: gdrive"
echo "   - Read-only access for deployment user"
echo ""
echo "5. Test NFS availability from London server:"
echo "   showmount -e 192.168.100.212"
echo ""
echo "6. Update share paths in setup-nas-mounts.sh if different:"
echo "   ORICO_SHARE=/actual/path/to/orico"
echo "   GDRIVE_SHARE=/actual/path/to/gdrive"